Repository microsoft/DirectXTex, pull requests merged in 2023-10, with the labels that each got.

#400 Read legacy files with a DDS_HEADER size of 24
  DirectXTex/DirectXTexDDS.cpp
Labels: dds

#402 Fixed -flist handling for filenames with spaces
  Texassemble/texassemble.cpp
  Texconv/texconv.cpp
  Texdiag/texdiag.cpp
Labels: bug, tools

#404 October 28, 2023
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  HISTORY.md
  README.md
  Texconv/texconv.cpp
Labels: maintainence
