Repository microsoft/DirectXTex, pull requests merged in 2023-09, with the labels that each got.

#388 Update Xbox with ARM32 architecture deprecation
  .nuget/directxtex_uwp.nuspec
  CMakePresets.json
  DirectXTex/DirectXTexP.h
  DirectXTex/DirectXTex_Windows10_2019.vcxproj
  DirectXTex/DirectXTex_Windows10_2022.vcxproj
  DirectXTex_Windows10_2019.sln
  DirectXTex_Windows10_2022.sln
  build/DirectXTex-GitHub-CMake-Dev17.yml
  build/DirectXTex-GitHub-CMake.yml
  build/DirectXTex-GitHub-Dev17.yml
  build/DirectXTex-GitHub-SDK-prerelease.yml
  build/DirectXTex-GitHub-SDK-release.yml
  build/DirectXTex-GitHub.yml
  build/Directory.Build.props
Labels: xbox

#391 September 2023 release [Xbox variant]
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  HISTORY.md
  README.md
Labels: xbox

#393 Support reading files with a DDS_PIXELFORMAT size of 24
  DirectXTex/DirectXTexDDS.cpp
Labels: dds

#394 DDS_FLAGS_PERMISSIVE flag to allow some file variants with header bugs
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexDDS.cpp
  Texconv/texconv.cpp
Labels: dds

#398 Update build pipelines for recent changes to windows-2022 ADO images
  build/DirectXTex-GitHub-MinGW.yml
  build/DirectXTex-GitHub-Test-Dev17.yml
Labels: maintainence
