Repository microsoft/DirectXTex, pull requests merged in 2023-08, with the labels that each got.

#383 Update with fixes from main branch since June 2023 release
  CMakeLists.txt
  DirectXTex/BCDirectCompute.cpp
  DirectXTex/DDS.h
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexDDS.cpp
  DirectXTex/d3dx12.h
  build/DirectXTex-config.cmake.in
Labels: xbox

#375 Add CompressEx and ConvertEx methods that report progress
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexCompress.cpp
  DirectXTex/DirectXTexCompressGPU.cpp
  DirectXTex/DirectXTexConvert.cpp
Labels: enhancement

#384 Add NO_WCHAR_T build option to CMake
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexDDS.cpp
  DirectXTex/DirectXTexHDR.cpp
  DirectXTex/DirectXTexTGA.cpp
  DirectXTex/DirectXTexWIC.cpp
  build/DirectXTex-GitHub-CMake-Dev17.yml
  build/DirectXTex-GitHub-CMake.yml
Labels: maintainence

#385 Update Xbox with latest changes from August 2023 work
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexCompress.cpp
  DirectXTex/DirectXTexCompressGPU.cpp
  DirectXTex/DirectXTexConvert.cpp
  DirectXTex/DirectXTexDDS.cpp
  DirectXTex/DirectXTexHDR.cpp
  DirectXTex/DirectXTexTGA.cpp
  DirectXTex/DirectXTexWIC.cpp
  DirectXTex/DirectXTexXbox.h
  DirectXTex/DirectXTexXboxDDS.cpp
  build/DirectXTex-GitHub-CMake-Dev17.yml
  build/DirectXTex-GitHub-CMake.yml
Labels: xbox

#386 Suppress some additional clang v16 warnings when upgrading to clangcl
  DirectXTex/DirectXTexP.h
Labels: maintainence

#387 AArch32 (ARM32) architecture deprecation
  .nuget/directxtex_uwp.nuspec
  CMakePresets.json
  DirectXTex/DirectXTex_Windows10_2019.vcxproj
  DirectXTex/DirectXTex_Windows10_2022.vcxproj
  DirectXTex_Windows10_2019.sln
  DirectXTex_Windows10_2022.sln
  build/DirectXTex-GitHub-CMake-Dev17.yml
  build/DirectXTex-GitHub-CMake.yml
  build/DirectXTex-GitHub-Dev17.yml
  build/DirectXTex-GitHub.yml
Labels: maintainence, uwp
