Repository microsoft/DirectXTex, pull requests merged in 2023-06, with the labels that each got.

#360 texconv: Added tgazeroalpha switch for some legacy TGA files
  Texconv/texconv.cpp
Labels: tools, tga

#336 Add .DDX Support
  Texconv/texconv.cpp
Labels: tools

#363 Fix CMake problem with /Zc:templateScope on older Windows SDKs
  CMakeLists.txt
  DirectXTex/d3dx12.h
Labels: conformance

#362 texconv: Added support for DXT5nm and RXGB DXT5 format variants
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexDDS.cpp
  Texconv/texconv.cpp
Labels: tools, dds

#364 tex tools updated with support for long file paths with Windows 10
  Auxiliary/DirectXTexEXR.cpp
  CMakeLists.txt
  Texassemble/Texassemble_Desktop_2019.vcxproj
  Texassemble/Texassemble_Desktop_2019.vcxproj.filters
  Texassemble/Texassemble_Desktop_2019_Win10.vcxproj
  Texassemble/Texassemble_Desktop_2019_Win10.vcxproj.filters
  Texassemble/Texassemble_Desktop_2022.vcxproj
  Texassemble/Texassemble_Desktop_2022.vcxproj.filters
  Texassemble/Texassemble_Desktop_2022_Win10.vcxproj
  Texassemble/Texassemble_Desktop_2022_Win10.vcxproj.filters
  Texassemble/settings.manifest
  Texassemble/texassemble.cpp
  Texconv/Texconv_Desktop_2019.vcxproj
  Texconv/Texconv_Desktop_2019.vcxproj.filters
  Texconv/Texconv_Desktop_2019_Win10.vcxproj
  Texconv/Texconv_Desktop_2019_Win10.vcxproj.filters
  Texconv/Texconv_Desktop_2022.vcxproj
  Texconv/Texconv_Desktop_2022.vcxproj.filters
  Texconv/Texconv_Desktop_2022_Win10.vcxproj
  Texconv/Texconv_Desktop_2022_Win10.vcxproj.filters
  Texconv/settings.manifest
  Texconv/texconv.cpp
  Texdiag/settings.manifest
  Texdiag/texdiag.cpp
  Texdiag/texdiag_Desktop_2019.vcxproj
  Texdiag/texdiag_Desktop_2019.vcxproj.filters
  Texdiag/texdiag_Desktop_2019_Win10.vcxproj
  Texdiag/texdiag_Desktop_2019_Win10.vcxproj.filters
  Texdiag/texdiag_Desktop_2022.vcxproj
  Texdiag/texdiag_Desktop_2022.vcxproj.filters
  Texdiag/texdiag_Desktop_2022_Win10.vcxproj
  Texdiag/texdiag_Desktop_2022_Win10.vcxproj.filters
Labels: tools

#366 June 2023 release [Xbox Variant]
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  Auxiliary/DirectXTexEXR.cpp
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexDDS.cpp
  DirectXTex/d3dx12.h
  HISTORY.md
  README.md
  Texassemble/Texassemble_Desktop_2019.vcxproj
  Texassemble/Texassemble_Desktop_2019.vcxproj.filters
  Texassemble/Texassemble_Desktop_2019_Win10.vcxproj
  Texassemble/Texassemble_Desktop_2019_Win10.vcxproj.filters
  Texassemble/Texassemble_Desktop_2022.vcxproj
  Texassemble/Texassemble_Desktop_2022.vcxproj.filters
  Texassemble/Texassemble_Desktop_2022_Win10.vcxproj
  Texassemble/Texassemble_Desktop_2022_Win10.vcxproj.filters
  Texassemble/settings.manifest
  Texassemble/texassemble.cpp
  Texconv/Texconv_Desktop_2019.vcxproj
  Texconv/Texconv_Desktop_2019.vcxproj.filters
  Texconv/Texconv_Desktop_2019_Win10.vcxproj
  Texconv/Texconv_Desktop_2019_Win10.vcxproj.filters
  Texconv/Texconv_Desktop_2022.vcxproj
  Texconv/Texconv_Desktop_2022.vcxproj.filters
  Texconv/Texconv_Desktop_2022_Win10.vcxproj
  Texconv/Texconv_Desktop_2022_Win10.vcxproj.filters
  Texconv/settings.manifest
  Texconv/texconv.cpp
  Texdiag/settings.manifest
  Texdiag/texdiag.cpp
  Texdiag/texdiag_Desktop_2019.vcxproj
  Texdiag/texdiag_Desktop_2019.vcxproj.filters
  Texdiag/texdiag_Desktop_2019_Win10.vcxproj
  Texdiag/texdiag_Desktop_2019_Win10.vcxproj.filters
  Texdiag/texdiag_Desktop_2022.vcxproj
  Texdiag/texdiag_Desktop_2022.vcxproj.filters
  Texdiag/texdiag_Desktop_2022_Win10.vcxproj
  Texdiag/texdiag_Desktop_2022_Win10.vcxproj.filters
Labels: xbox
