Repository microsoft/DirectXTex, pull requests merged in 2023-12, with the labels that each got.

#420 ADO OneFuzz pipeline updated with setup script
  build/DirectXTex-OneFuzz.yml
  build/OneFuzzConfig.json
  build/onefuzz-setup.ps1
Labels: maintainence

#421 PPM TGA HDR bounds updates on readers
  DirectXTex/DirectXTexHDR.cpp
  DirectXTex/DirectXTexP.h
  DirectXTex/DirectXTexTGA.cpp
  Texconv/PortablePixMap.cpp
  build/OneFuzzConfig.json
  build/onefuzz-setup.ps1
Labels: bug

#423 Have CMake generate pkg-config file for library
  CMakeLists.txt
  build/DirectXTex.pc.in
  build/JoinPaths.cmake
Labels: enhancement

#429 Missing offset boundary check in TGA reader
  DirectXTex/DirectXTexTGA.cpp
Labels: bug, tga

#422 Code review to silence some portability warnings
  DirectXTex/BC.h
  DirectXTex/BC6HBC7.cpp
  DirectXTex/BCDirectCompute.h
Labels: conformance

#428 Fix warnings in tools for MinGW
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  Texassemble/AnimatedGif.cpp
  Texassemble/texassemble.cpp
  Texconv/ExtendedBMP.cpp
  Texconv/PortablePixMap.cpp
  Texconv/texconv.cpp
  Texdiag/texdiag.cpp
Labels: maintainence, tools
