Repository microsoft/DirectXTex, pull requests merged in 2024-01, with the labels that each got.

#431 December 31, 2023
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  HISTORY.md
  README.md
Labels: maintainence

#434 Add bound on depth values to fix warnings in MinGW 13.2
  CMakeLists.txt
  DirectXTex/BC6HBC7.cpp
  DirectXTex/DirectXTexImage.cpp
  DirectXTex/DirectXTexMipmaps.cpp
Labels: conformance

#436 Spelling fix in comments
  Auxiliary/DirectXTexEXR.cpp
  Auxiliary/DirectXTexEXR.h
  Auxiliary/DirectXTexXbox.h
  Auxiliary/DirectXTexXboxD3D11X.cpp
  Auxiliary/DirectXTexXboxD3D12X.cpp
  Auxiliary/DirectXTexXboxDDS.cpp
  Auxiliary/DirectXTexXboxDetile.cpp
  Auxiliary/DirectXTexXboxImage.cpp
  Auxiliary/DirectXTexXboxTile.cpp
  CMakeLists.txt
Labels: maintainence

#437 OneFuzz parameter adjustment
  build/OneFuzzConfig.json
Labels: maintainence

#438 CMake update to install EXEs
  CMakeLists.txt
Labels: tools

#439 OneFuzz ADO pipeline adjustments
  build/DirectXTex-OneFuzz.yml
Labels: maintainence

#440 Don't allow TGA reader to read images larger than 4GB even in 64-bit
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexHDR.cpp
  DirectXTex/DirectXTexImage.cpp
  DirectXTex/DirectXTexTGA.cpp
Labels: maintainence, tga

#407 Create options/sources for JPEG/PNG support
  Auxiliary/DirectXTexJPEG.cpp
  Auxiliary/DirectXTexJPEG.h
  Auxiliary/DirectXTexPNG.cpp
  Auxiliary/DirectXTexPNG.h
  CMakeLists.txt
  CMakePresets.json
  DirectXTex/DirectXTexP.h
  README.md
  Texassemble/texassemble.cpp
  Texconv/texconv.cpp
  Texdiag/texdiag.cpp
  build/DirectXTex-config.cmake.in
Labels: enhancement, wsl

#441 Merge Xbox xtexconv tool into mainline via CMake
  CMakeLists.txt
  DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj
  DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj
  README.md
  Texconv/texconv.cpp
Labels: tools, xbox

#445 CMake code review
  CMakeLists.txt
Labels: maintainence
