Repository microsoft/DirectXTex, pull requests merged in 2024-08, with the labels that each got.

#493 Update CMake to handle ARM64EC with VS Generator
  build/CompilerAndLinker.cmake
Labels: maintainence

#483 Add cubemap support for OpenEXR
  Auxiliary/DirectXTexEXR.cpp
Labels: enhancement, exr

#494 Additional code review for OpenEXR
  Auxiliary/DirectXTexEXR.cpp
Labels: enhancement

#495 Minor SAL fix
  ScreenGrab/ScreenGrab11.h
  ScreenGrab/ScreenGrab12.h
  ScreenGrab/ScreenGrab9.h
Labels: maintainence

#497 Xbox auxiliary EncodeDDSHeader helper exposed as public function
  Auxiliary/DirectXTexEXR.cpp
  Auxiliary/DirectXTexXbox.h
  Auxiliary/DirectXTexXboxD3D11X.cpp
  Auxiliary/DirectXTexXboxD3D12X.cpp
  Auxiliary/DirectXTexXboxDDS.cpp
  CMakeLists.txt
  DirectXTex/DDS.h
  DirectXTex/DirectXTexDDS.cpp
  Texconv/PortablePixMap.cpp
  build/CompilerAndLinker.cmake
Labels: xbox

#499 Add VCPKG usage to GitHub Actions
  .github/workflows/main.yml
  .github/workflows/test.yml
  .github/workflows/vcpkg.yml
  .gitignore
  Auxiliary/DirectXTexEXR.cpp
  CMakePresets.json
  build/CompilerAndLinker.cmake
  build/vcpkg.json
Labels: maintainence

#500 D3DFMT_A2W10V10U10 fix for ScreenGrab DX9
  ScreenGrab/ScreenGrab9.cpp
Labels: bug, dds

#501 Support loading legacy DDS files using mixed channel formats
  DirectXTex/DirectXTexDDS.cpp
Labels: enhancement, dds
