Repository microsoft/DirectXTex, pull requests merged in 2024-02, with the labels that each got.

#448 Update GDK projects and ADO pipelines
  DirectXTex/DirectXTex_GDK_2019.vcxproj
  DirectXTex/DirectXTex_GDK_2022.vcxproj
  build/DirectXTex-GitHub-WSL-11.yml
  build/DirectXTex-GitHub-WSL.yml
  build/DirectXTex-OneFuzz.yml
Labels: maintainence

#449 Workaround clang/LLVM bug with /fp:fast+SSE+float_control
  CMakeLists.txt
  DDSTextureLoader/DDSTextureLoader11.cpp
  DDSTextureLoader/DDSTextureLoader12.cpp
  DDSTextureLoader/DDSTextureLoader9.cpp
  DirectXTex/BC6HBC7.cpp
  DirectXTex/DirectXTexConvert.cpp
  DirectXTex/DirectXTexD3D11.cpp
  DirectXTex/DirectXTexD3D12.cpp
  DirectXTex/DirectXTexTGA.cpp
  DirectXTex/d3dx12.h
  Texconv/PortablePixMap.cpp
Labels: conformance

#450 Fix -Wextra-semi-stmt warning
  Texconv/texconv.cpp
Labels: conformance

#451 Update CMake to work with Intel compilers
  CMakeLists.txt
  CMakePresets.json
  DirectXTex/DirectXTexUtil.cpp
  DirectXTex/DirectXTexWIC.cpp
  WICTextureLoader/WICTextureLoader11.cpp
  WICTextureLoader/WICTextureLoader12.cpp
  WICTextureLoader/WICTextureLoader9.cpp
Labels: conformance

#452 CMake refactor
  CMakeLists.txt
  DDSView/DDSView_Desktop_2019.vcxproj
  DDSView/DDSView_Desktop_2022.vcxproj
  DirectXTex/DirectXTexP.h
  DirectXTex/DirectXTex_Desktop_2019.vcxproj
  DirectXTex/DirectXTex_Desktop_2019_Win10.vcxproj
  DirectXTex/DirectXTex_Desktop_2022.vcxproj
  DirectXTex/DirectXTex_Desktop_2022_Win10.vcxproj
  DirectXTex/DirectXTex_GDK_2019.vcxproj
  DirectXTex/DirectXTex_GDK_2022.vcxproj
  DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj
  DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj
  DirectXTex/DirectXTex_Windows10_2019.vcxproj
  DirectXTex/DirectXTex_Windows10_2022.vcxproj
  build/CompilerAndLinker.cmake
Labels: maintainence

#368 TexAssemble: Support for 2D Texture with custom mip maps using "from-mips" argument
  Texassemble/texassemble.cpp
Labels: tools

#453 Fix build breaks for texassemble
  Texassemble/texassemble.cpp
Labels: tools

#455 Update YAML pipeline triggers
  build/DirectXTex-GitHub-CMake-Dev17.yml
  build/DirectXTex-GitHub-CMake.yml
Labels: maintainence

#456 February 21, 2024
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  HISTORY.md
  README.md
Labels: maintainence

#457 Hotfix for CMake switch order
  build/CompilerAndLinker.cmake
Labels: bug

#459 Xbox auxiliary optimization for tiling
  Auxiliary/DirectXTexXboxDetile.cpp
  Auxiliary/DirectXTexXboxTile.cpp
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexUtil.cpp
Labels: xbox

#460 Fixed unreferenced formal parameter warning
  Auxiliary/DirectXTexXboxDetile.cpp
  Auxiliary/DirectXTexXboxTile.cpp
  DirectXTex/DirectXTexUtil.cpp
Labels: bug
