Repository microsoft/DirectXTex, pull requests merged in 2024-09, with the labels that each got.

#503 Fix exporting R8 files as PNG using libpng
  Auxiliary/DirectXTexPNG.cpp
Labels: bug, wsl

#504 ADO test pipeline updates
  Auxiliary/DirectXTexJPEG.cpp
  CMakePresets.json
  build/DirectXTex-GitHub-Test-Dev17.yml
  build/DirectXTex-GitHub-Test.yml
Labels: maintenance, wsl

#502 Update CMake to specify FXC.EXE to use
  .github/workflows/test.yml
  .github/workflows/wsl.yml
  Auxiliary/DirectXTexPNG.cpp
  CMakeLists.txt
  DirectXTex/DirectXTexDDS.cpp
  DirectXTex/Shaders/CompileShaders.cmd
  build/CompilerAndLinker.cmake
  build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
  build/DirectXTex-GitHub-Dev17.yml
  build/DirectXTex-GitHub-GDK-Dev17.yml
  build/DirectXTex-GitHub.yml
  build/vcpkg.json
Labels: maintenance, conformance

#505 September 4, 2024
  .github/workflows/wsl.yml
  .nuget/directxtex_desktop_2019.nuspec
  .nuget/directxtex_desktop_win10.nuspec
  .nuget/directxtex_uwp.nuspec
  CHANGELOG.md
  CMakeLists.txt
  DirectXTex/DirectXTex.h
  README.md
  build/Directory.Build.props
  build/onefuzz-setup.ps1
  build/preparerelease.ps1
  build/versioninfo.ps1
Labels: maintenance

#506 Update BWOI support in VC projects
  DirectXTex/DirectXTex_Desktop_2019.vcxproj
  DirectXTex/DirectXTex_Desktop_2019_Win10.vcxproj
  DirectXTex/DirectXTex_Desktop_2022.vcxproj
  DirectXTex/DirectXTex_Desktop_2022_Win10.vcxproj
  DirectXTex/DirectXTex_GDK_2019.vcxproj
  DirectXTex/DirectXTex_GDK_2022.vcxproj
  DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj
  DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj
  DirectXTex/DirectXTex_Windows10_2022.vcxproj
Labels: maintenance

#510 Build pipeline updates
  build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
  build/DirectXTex-GitHub-CMake-Xbox.yml
  build/DirectXTex-GitHub-GDK-Dev17.yml
  build/DirectXTex-GitHub-GDK.yml
  build/DirectXTex-GitHub-SDK-prerelease.yml
  build/DirectXTex-GitHub-SDK-release.yml
  build/Directory.Build.props
  build/placeholder.xvd
Labels: maintenance

#511 ADO pipeline for SDK builds
  build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
  build/DirectXTex-GitHub-CMake-Xbox.yml
  build/DirectXTex-GitHub-GDK-Dev17.yml
  build/DirectXTex-GitHub-GDK.yml
  build/DirectXTex-GitHub-SDK-prerelease.yml
  build/DirectXTex-GitHub-SDK-release.yml
  build/Directory.Build.props
  build/SetupBWOI.targets
Labels: maintenance

#516 Add BytesPerBlock helper
  DirectXTex/DirectXTex.h
  DirectXTex/DirectXTexUtil.cpp
Labels: enhancement
